//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZXMAK2.Host.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZXMAK2.Host.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuColdReset_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuColdReset_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuFileOpen_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuFileOpen_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuFileSave_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuFileSave_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuFullScreen_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuFullScreen_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuMaxSpeed_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuMaxSpeed_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuPause_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuPause_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuQuickLoad_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuQuickLoad_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuResume_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuResume_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuSettings_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuSettings_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuWarmReset_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuWarmReset_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmuWindowed_32x32 {
            get {
                object obj = ResourceManager.GetObject("EmuWindowed_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;KeyboardStateMapper xmlns=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;!-- 
        ///    Managed DirectX to ZXMAK2 key mapping
        ///    
        ///    Name=ZXMAK2.Host.Entities.Key
        ///    Value=Microsoft.DirectX.DirectInput.Key
        ///    --&gt;
        ///    &lt;Key Name=&quot;D1&quot; Value=&quot;D1&quot; /&gt;
        ///    &lt;Key Name=&quot;D2&quot; Value=&quot;D2&quot; /&gt;
        ///    &lt;Key Name=&quot;D3&quot; Value=&quot;D3&quot; /&gt;
        ///    &lt;Key Name=&quot;D4&quot; Value=&quot;D4&quot; /&gt;
        ///    &lt;Key Name=&quot;D5&quot; Value=&quot;D5&quot; /&gt;
        ///    &lt;Key Name=&quot;D6&quot; Value=&quot;D6&quot; /&gt;
        ///    &lt;Key Name=&quot;D7&quot; Value=&quot;D7&quot; /&gt;
        ///    &lt;Key Na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keyboard_Mdx {
            get {
                return ResourceManager.GetString("Keyboard_Mdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;KeyboardStateMapper xmlns=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///    &lt;!-- 
        ///    WinForms to ZXMAK2 key mapping
        ///    
        ///    Name=ZXMAK2.Host.Entities.Key
        ///    Value=System.Windows.Forms.Keys
        ///    --&gt;
        ///    &lt;Key Name=&quot;D1&quot; Value=&quot;D1&quot; /&gt;
        ///    &lt;Key Name=&quot;D2&quot; Value=&quot;D2&quot; /&gt;
        ///    &lt;Key Name=&quot;D3&quot; Value=&quot;D3&quot; /&gt;
        ///    &lt;Key Name=&quot;D4&quot; Value=&quot;D4&quot; /&gt;
        ///    &lt;Key Name=&quot;D5&quot; Value=&quot;D5&quot; /&gt;
        ///    &lt;Key Name=&quot;D6&quot; Value=&quot;D6&quot; /&gt;
        ///    &lt;Key Name=&quot;D7&quot; Value=&quot;D7&quot; /&gt;
        ///    &lt;Key Name=&quot;D8&quot; Value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keyboard_WinForms {
            get {
                return ResourceManager.GetString("Keyboard_WinForms", resourceCulture);
            }
        }
    }
}
